[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
select = ["E","F","I","W","UP","B"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["ui","utils"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
